### PR TITLE
resolved 2 issues

### PR DESCRIPTION
**Pull request by RAJAGOPALAN-GANGADHARAN**
1.Added a required dependency
2.Changed Intro text

### CODE REVIEW

**Comment by TyVik** [comment]
You did it :) but not until the end. You should also update existing translations https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#message-files. Right now just keep old translation for new text.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@TyVik Russian translations right?

**Comment by TyVik** [comment]
@RAJAGOPALAN-GANGADHARAN yes, right.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@TyVik yeah sure

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@TyVik Its been a long time. Still active on this one?

**Comment by TyVik** [comment]
Hi! Yep, but could you please update your master from upstream? Looks like too many conflicts and I got confused in them.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@TyVik please dont get annoyed can you tell me how should i do it?

**Comment by TyVik** [comment]
https://help.github.com/articles/syncing-a-fork/

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@TyVik thank you for the article will read and do it

**Pull request closed without merging**
