### PR TITLE
change to use class properties

### LINKED ISSUE #248: Use class properties
Use class properties instead of assign in the constructor:
https://github.com/TyVik/geopuzzle/blob/7abd23cac1995dd5366a38ea9e79e4cf700e100a/frontend/workshop/index.jsx#L13

### PR DESCRIPTION
**Pull request by vinmaster**
closes https://github.com/TyVik/geopuzzle/issues/248

### CODE REVIEW

**Comment by ghost** [comment]
### Changes to your CodeSee Architecture Map:
[View a CodeSee Map of these changes](https://app.codesee.io/r/prs?id=4509&src=https%3A%2F%2Fgithub.com%2FTyVik%2Fgeopuzzle)

View [this PR diagram as an interactive map](https://app.codesee.io/r/prs?id=4509&src=https%3A%2F%2Fgithub.com%2FTyVik%2Fgeopuzzle)

View [more CodeSee Maps](https://app.codesee.io/r/maps?src=https%3A%2F%2Fgithub.com%2FTyVik%2Fgeopuzzle)

#### Legend
CodeSee Map Legend

**Comment by TyVik** [comment]
Passing state as props is very tricky... I mean state must be defined inside the component. Simultaneously, I'd like to avoid using global environments (like __ORDER__) in any components. So, there are 2 steps:
- change back this.state definition
- pass window.__ORDER__.map(...) as props and use this prop instead of this.orderOptions
- update tests if needed

**Comment by vinmaster** [comment]
> * pass window.**ORDER**.map(...) as props and use this prop instead of this.orderOptions

Hi @TyVik , I've made the changes. I am not sure if this is what you meant by updating the orderOptions. It's now passing as `prop` and I've updated the places that `orderOptions` is changed

**Comment by TyVik** [comment]
Not yet (`prop` is redundant), but I'll finish it in master. Thank you!

**Comment by TyVik** [comment]
Just FYI I told about https://github.com/TyVik/geopuzzle/pull/728/files#diff-4e3429d2df961f5539a3148aabea103cb2321445693387dd3f4c8bc6b0613bf7.

**Pull request merged**
